### PR TITLE
Dependcy removal

### PR DESCRIPTION
**Pull request by nuggreat**
resolves issue #115

### CODE REVIEW

**Comment by scimas** [comment]
#100 already does all these things and some more. I haven't tested those changes, but the common code alterations look basically identical between this and that pull request. But it doesn't remove `spec_char.ksm` from KSLib. I suggest that we merge #100 and remove spec_char.ksm in a following commit.

**Comment by nuggreat** [comment]
The problem with pulling in #100 is that lib_input_string will be broken as one of the things i did was to change the use of the iterator used for the final string concatenation over to a for loop.
So it would just be more work to pull in the older PR and then generate a 2nd one to remove the spec_char.ksm and all associated files and then fix the problem with lib_input_string.
Where as if we just pull in my PR and then close out the older PR and issue that is only a single pull.

**Comment by scimas** [comment]
It also does changes to `lib_seven_seg.ks`. So if we want those changes, there is going to be another PR anyway. You can do the iteration change and spec_char removal on the new base.

**Comment by nuggreat** [comment]
I would prefer to only have to edit two file as apposed to edit one file and delete three others.

Also the type and number checks in `lib_seven_seg.ks` could be expanded to better match the intent because as it stands any number greater than 9 will just result in a 9 being displayed even if the passed in number is `10000`

**Comment by nuggreat** [comment]
Cool so do you want me to add in the changes to `lib_seven_seg` to this PR or generate a new one with said changes.

**Comment by scimas** [comment]
Better make it a different PR, there's nothing about dependencies in that one.

**Pull request merged**
