### PR TITLE
Initial version of docking library

### PR DESCRIPTION
**Pull request by fmatosqg**
Draft of a library usefull for docking, including pointing into some direction and reducing speed relative to target.

Please don't merge it yet.

### CODE REVIEW

**Comment by fmatosqg** [comment]
The last pushed version is stable enough to be merged, so please go forward :)

**Comment by space-is-hard** [comment]
@fmatosqg Either myself or @TDW89 will give these a try soon-ish. Thanks :)

**Comment by TDW89** [comment]
Will take a proper look at this this afternoon but from first glance it could use documentation (look in the doc folder for examples)

**Comment by fmatosqg** [comment]
Yeah I should have it started by now. I'm afraid of refactoring some things based on feedback and changing contracts/parameters, but I should have at least the bulk of it under way soon-ish.

What about style, how does it look? I didn't pay any attention to the style guide at all, so I don't even know whether I'm almost OK or far from it.

**Comment by TDW89** [comment]
Ok had a bit of time to go through this.
Its not a bad non-RCS docking script.
But I think you may have missed difference between a library and script.
A library should contain a set of similar generic use functions that make writing a script for a specific task faster / easier. (one of the others may be able to provide a better definition).

My personal feeling is that a function should return information and leave it to the script to decide what to do with that info, a good example of this would be lib_pid. The function in the lib file returns the updated value but leaves it to the script to lock / update the throttle / whatever is being controlled. 

Also unless it is the purpose of the function it is usually best to keep printing to the terminal out of it to avoid messing with any interface / readout users have set up.

Anyway some of the functions in your lib file are more generic functions (not docking related):
message,
initvecdraw,
etc.

If you could move them into the example script, or create a separate lib file. A message lib that used an init function to set up a style then let you specify a preset style for a message could be useful.
```
set err to message_style(20, 1, 12, red, true).
message( err, "this is an error message").
```
All that said with a bit of re-jigging to move more generic functions and some of the other more script like parts over to the example file a library containing a bunch of docking tools / info would be great. (+ any other library ideas you have)

**Comment by Dunbaratu** [comment]
IMO there should be a place to put full executable examples too, not just library functions.,  Maybe in another folder?

**Comment by TDW89** [comment]
Would it make sense to use the examples folder for example scripts that don't necessarily use the library as well as those that do?

**Comment by Dunbaratu** [comment]
hmm. not sure.  I'm leaving that up to you.  I'm just saying that a place for fully working scripts would be a good thing - as it's a thing people often request and they make for good teaching examples.

**Comment by fmatosqg** [comment]
I think this won't add much value as a library, at least I had more of a subsystem mentality when writing it. Maybe it would fit better as a standalone script.

Hmm looks like it needs updating to the last kOS anyway.

**Pull request closed without merging**
