### PR TITLE
Program: Q_terminal

### PR DESCRIPTION
**Pull request by abenkovskii**
In case someone is bored typing long program names into the terminal.

### CODE REVIEW

**Comment by Dunbaratu** [comment]
I don't get the name.  Why is it called q terminal ?

**Comment by abenkovskii** [comment]
Quick terminal. The other way to do this: add auto completion for file names on the current volume to the kOS terminal.

**Comment by abenkovskii** [comment]
@akrasuski1 What do you think about it? Keep in mind that my intent is to eventually make it as space efficient as could be without hurting the readability too much.

**Comment by akrasuski1** [comment]
Hmmm. If you're asking about code quality, I'm quite fine with it. But I don't really get the use case. Although I haven't installed it, from the code I guess the typical use case is: 
1. Type "run q_run".
2. Select program.
But in my opinion, it's barely faster than just typing the whole name of the program (and with q_switch and the rest, the situation is even worse). On top of that, if user has little files, they are likely to be short. On the other hand, if they are long, there is high probability there are many of them, rendering your list slow to move through as well. It might be useful if one does not remember the exact name of the program - but in such case, one can always just list files as stock kOS allows.

You asked if I would find it useful, as I use run command often. But the truth is, I usually test just one program at once, and after I want to try new version, I can simply use up arrow and enter (two keystrokes in total) to repeat last command.

**Comment by abenkovskii** [comment]
I personally use q_run to run examples - they are usually at the start of the list. Probably because "e" < "l". But actually yes I don't think that it worth to be merged.

**Pull request closed without merging**
