### PR TITLE
Changed PID_array creation to use LIST() constructor, instead of adding ...

### PR DESCRIPTION
**Pull request by austinjames314**
...each element one-by-one to an empty list.

This is my first time doing this, so apologies if it's screwed up or improper in some way.

### CODE REVIEW

**Comment by Dunbaratu** [comment]
There's more than one place in the file the change can be made.

I'll get around to pulling this after erendrake fixes he public ZIP's out there.  It seems to be that the LIST() constructor change didn't quit make it from the dev platform out to the zip file.

**Comment by Dunbaratu** [comment]
I'll pull this so you get credit for what you did, but I'll also be adding the other places as well where it can be changed.

**Comment by Dunbaratu** [comment]
Actually on further examination, there's no gain to be had by using the constructor elsewhere other than that one place, so I won't be doing further changes after all.

**Comment by austinjames314** [comment]
Yeah I was wondering what I had missed. First (tiny) contribution! Thanks!

**Pull request merged**
