### PR TITLE
Added stripper utility.

### LINKED ISSUE #6: Should we put some standard stripper utilities here?
One thing I often do is run a "stripper" script that compacts all my kerboscript code into a form where all the comments and indenting space is removed.

It occurs to me that maybe either putting utility scripts here (they'd have to be OS-dependant to some extent) that do that for others may be nice, or even more ambitious still, we could make a tool that automatically does this with all submitted code and provides a "stripped" folder with the stripped versions.  Note, the original would be preserved as well.  This would be a second copy of the script.

It would be nice if people didn't feel constrained to have to write their scripts compactly just to reduce footprint, and instead could make them well indented and commented, especially as putting scripts here is meant to be a useful teaching tool as well as a library.

(while I'm at it - header comment detection and stripping to auto-gen MD document files could be pretty good too - but that should be a separate issue)

### PR DESCRIPTION
**Pull request by akrasuski1**
This should fix #6, at least for Unix environments.

### CODE REVIEW

**Comment by abenkovskii** [comment]
I probably spotted a bug. I'll create a linux testing environment to test it.

**Comment by abenkovskii** [comment]
Confirmed.
This:
```
set bug_string to "bug//bug".
```
Turns into this:
```
set bug_string to "bug
```

**Comment by abenkovskii** [comment]
```
print 42. // // bug or feature?
```
turns into:
```
print 42. //
```
Though for most practical situations this regexp is OK

**Comment by akrasuski1** [comment]
This was not an intended behaviour, but fixing this would be hard. I'd  say such a situation is rare enough we can live with it.

Deleting branch.

**Pull request merged**
