### PR TITLE
Adds beep character to the spec_char 

### PR DESCRIPTION
**Pull request by abenkovskii**
I also compacted spec_char a bit using this information: https://github.com/KSP-KOS/KOS/blob/develop/src/kOS.Safe/Compilation/CompiledObject-doc.md

### CODE REVIEW

**Comment by abenkovskii** [comment]
@benthor, if you are using TELNET this is for you.

**Comment by benthor** [comment]
very cool, thank you!

**Comment by abenkovskii** [comment]
@akrasuski1, could you please check out this?

**Comment by akrasuski1** [comment]
I can't, because under Ubuntu terminal is set to not make any noises while printing '\a' character. Fixing this is quite a bit of hassle.

Either way, example file has two typos:
`TELENET` -> `TELNET`
`here` -> `hear`

**Comment by abenkovskii** [comment]
Thank you. Is everything else OK?

**Comment by akrasuski1** [comment]
Yeah, though I did not check much - the endl and quote were already there, after all. So I didn't check the  only thing introduced in this PR.

**Comment by Dunbaratu** [comment]
If you'd like, you can make an issue over in kOS for me to add a BEEP to the in-game GUI terminal that will respond to the existence of the 0x0007 unicode char on the output stream.  Then this would work in both places.

I was meaning to do it but I keep forgetting.  Putting it in the issues list will help (there is an issue already but it's mangled up with other unrelated requests).

**Comment by akrasuski1** [comment]
Sure - I just thought you were too busy doing short circuiting and dother things.

**Comment by Dunbaratu** [comment]
Just a warning as I started to look into the implementation of this, the current way the telnet system works, using the beep char from spec_char.ksm in a telnet will confuse the heck out of the telnet repainting system.  This is because the kOS telnet repainting system doesn't realize the beep character doesn't really take a space on the screen.  It gets put into the screen buffer as if it takes a spot, so if you printed ``print beep + "hi".`` the memory frame buffer THINKS your screen cells look like this:
```
+---+---+---+---+---+
| \a| h | i |   |   |   |
+---+---+---+---+---+
```
When they actually look like this:
```
+---+---+---+---+---+
| h | i |   |   |   |   |
+---+---+---+---+---+
```
(It doesn't know that the \a character doesn't really "print" and take up a cell.)  This messes with the algorithm.  I'm fixing it now in my new PR but this is just a warning that it doesn't quite work right as-is before I get that PR in.)

**Comment by abenkovskii** [comment]
Should it be merged to the master or to the develop branch? @akrasuski1, what do you think?

**Comment by erendrake** [comment]
I think it is good practice to always merge features into develop and then peroidacly merge develop into master. Just my 2 cents

**Comment by abenkovskii** [comment]
@erendrake Well... develop is supposed to follow the current kOS/develop state while master is a version for the current kOS release. In my view KSLib is not yet at that state of maturity when updating the main branch at the same rate the kOS releases is the right thing to do.

**Comment by abenkovskii** [comment]
@erendrake A problem with this PR is that the latest kOS release doesn't process a character 0x7  properly: https://github.com/KSP-KOS/KSLib/pull/61#issuecomment-104409720. That's why I think it should be in the develop branch.

**Comment by erendrake** [comment]
@abenkovskii i am sorry if i was unclear. i think that you should always merge new features into develop.

**Comment by abenkovskii** [comment]
@erendrake We need a version of KSLib compatible with the latest kOS release too. Do you think that the name "develop" is too ambiguous? May be it should me in a separate fork? The "next release" version gives us the ability to update the main KSLib to account for all breaking changes and new features as soon as the new kOS version releases.

**Comment by TDW89** [comment]
Would the following branches make sense:
 * Master     - The release branch, in line with the current kOS release and containing only complete, working and  documented scripts.
 * Develop  - (possibly call it Future if develop is to ambiguous) Similar to the master branch but incorporating scripts and script updates that take advantage of features only currently in the development branch of kOS (to be merged with the master branch when kOS updates).
 * Testing    - A branch for merging work into for group testing and feedback before it is committed to either of the main branches.

**Comment by space-is-hard** [comment]
@TDW89 Can we discuss your branch suggestions on Slack in a couple hours?

**Comment by TDW89** [comment]
@space-is-hard i can stay round for a bit it has just gone midnight here so it will probably have to be a quick descussion

**Pull request closed without merging**
