### PR TITLE
lib_lazcalc - more improvements

### PR DESCRIPTION
**Pull request by space-is-hard**
-Doc updated to include the name of the function.
-Doc updated to clarify that input altitude is in kilometers
-Doc updated to clarify input sterilization procedures

-Function now pulls the current vessel's inclination at the start of the
script. This avoids having two or more slightly different latitude
values being used in the calculations due to the script taking more than
one physics tick to complete
-Function will now throw an error and print a message if the input
target altitude is less than sea level
-Function now corrects impossible inclinations based on easterly or
westerly launches
-Function now prints message warning user of impossible inclination and
of automatic correction

### CODE REVIEW

**Comment by abenkovskii** [comment]
@erendrake Sometimes we need a system of exceptions and warnings in kerboscript.
@space-is-hard Printing a warning in case of wrong inclination might mess up someone's launch script custom readings display.

**Comment by space-is-hard** [comment]
Unfortunately I don't have any other way of warning the user that A) they can't reach the inclination they're asking for and B) the function automatically corrects this

**Comment by abenkovskii** [comment]
Never tried this: http://ksp-kos.github.io/KOS_DOC/commands/terminalgui.html#global:HUDTEXT but it might help.

**Comment by space-is-hard** [comment]
Made the change to HUDTEXT(). It looks surprisingly nice.

**Comment by abenkovskii** [comment]
Works nice.

**Pull request merged**
