### PR TITLE
Added simple menu and number input.

### PR DESCRIPTION
**Pull request by akrasuski1**
Now you can for example ask for apoapsis or something.

### CODE REVIEW

**Comment by abenkovskii** [comment]
Have you looked at lib_ag_list_dialog? I thought it does the same thing.

**Comment by Dunbaratu** [comment]
I was wondering the same thing.  I didn't look in too much detail because I switched contexts back to C# mod work.

**Comment by abenkovskii** [comment]
Though I like your implementation of menu more. Not because of the graphics but:
1. For a menu string is better return value type when integer. I realized it after working with my implementation. I found myself always comparing menu output with constants in a giant if...else if...else if. Changing return type to string will make it self explanatory.
2. Your interface (for a program that uses it) is simpler

**Comment by abenkovskii** [comment]
@akrasuski1 Why do you have the number input dialog in the same file?

**Comment by abenkovskii** [comment]
@akrasuski1 I have another idea how number input can work. I'll submit a PR to this PR.

**Comment by abenkovskii** [comment]
@akrasuski1 Check out this:
https://github.com/akrasuski1/KSLib/pull/1

**Comment by abenkovskii** [comment]
Other than that I have no objections. I'll remove menu_dialog from my lib_ag_list_dialog after this is pulled.

**Comment by abenkovskii** [comment]
@akrasuski1 Prefix "make" is often used for factory functions that create and return some complex structure. That's why I renamed "make_menu" to "open_menu".

**Comment by akrasuski1** [comment]
How about this?

**Comment by abenkovskii** [comment]
@Dunbaratu No objections. Ready to merge

**Pull request merged**
