### PR TITLE
Create lib_geodec

### PR DESCRIPTION
**Pull request by penatoliy**
geo coordinates to decart coordinates converter.

### CODE REVIEW

**Comment by space-is-hard** [comment]
I understand underscores prefixing variable names is a C++ thing; Is there a reason you're using them (and five of them at a time) here in kerboscript?

**Comment by Dunbaratu** [comment]
It's not a C++ thing.  It's just a generic naming scheme used in many languages, like picking uppercase versus lowercase first letter has meaning in different naming schemes.   It's not a standard I like, but it isn't mandated by C++.  It's just something some of the standard libraries for C have used.

**Comment by penatoliy** [comment]
fix it for you will =) i use this prefix for prevent collision`s.
iam no code in c/c++ =) only basic(autoit) and delphi.

This code writed for geoposition prediction. you can find future spot easy in decart coordinates, then convert it back)

**Comment by TDW89** [comment]
@penatoliy 
Could you add an example script and a doc file for your lib (check out the existing ones for other scripts if you would like examples).
then this should be ready to pull :-)

**Pull request merged**
