### PR TITLE
Added evaluate_function to lib_exec

### PR DESCRIPTION
**Pull request by abenkovskii**
Evaluates a function with given arguments and returns the result.

### CODE REVIEW

**Comment by abenkovskii** [comment]
@akrasuski1 Try this out.

**Comment by akrasuski1** [comment]
Looks ok.

**Comment by abenkovskii** [comment]
Looks or works ok? (I haven't tested it enough yet)

**Comment by akrasuski1** [comment]
Looks. I might test it in an hour or two.

**Comment by abenkovskii** [comment]
@TDW89 What do you think about this feature.

**Comment by TDW89** [comment]
Will give it a test run in a bit but after thinking abut it i can see some interesting uses for it

**Comment by abenkovskii** [comment]
@TDW89 Technically everything you can do with lib_exec you can do with `execute`. `evaluate` and `evaluate_function` are just wrappers that make your code nicer and your life easier.

**Comment by abenkovskii** [comment]
@TDW89 Confirmed that it's working in Slack.

**Pull request merged**
