### PR TITLE
lib_exec documentation update

### PR DESCRIPTION
**Pull request by abenkovskii**
issue: #52

### CODE REVIEW

**Comment by abenkovskii** [comment]
@akrasuski1 Could you please check out this?

**Comment by akrasuski1** [comment]
I think you should emphasize the fact that `execute` must be called **with** the dot in the end of the string, while `evaluate` must not. I was stuck on that for a few moments the first time I saw the library.

> parameter_list - list of strings, parameters to pass to the function

It does not have to be list of strings.

**Comment by abenkovskii** [comment]
@akrasuski1, could you check this out once again please?

**Comment by abenkovskii** [comment]
@akrasuski1 Fixed it now.

**Comment by akrasuski1** [comment]
Great, no more objections.

**Comment by abenkovskii** [comment]
Thanks for your review.
BTW did you notice this big green button:
image?

**Comment by abenkovskii** [comment]
Thanks.

**Pull request merged**
