### PR TITLE
Create example_lib_menu.ks

### PR DESCRIPTION
**Pull request by akrasuski1**
Added example to my lib.

### CODE REVIEW

**Comment by abenkovskii** [comment]
Next time I'd recommend to adding an example to the same PR

**Comment by akrasuski1** [comment]
OK, I'm quite new to Github, so I don't really know the workflow there - especially the PR mechanics.

**Comment by abenkovskii** [comment]
See the line "Add more commits by pushing to the <your_brunch_name> branch on <your_repo_name>." at the bottom of this page above big green sign "This pull request can be automatically merged".

**Comment by abenkovskii** [comment]
@akrasuski1 You might want to update the example now

**Comment by akrasuski1** [comment]
Yeah, so maybe I'll add them to the other PR. Is there a way to delete this one?

**Comment by abenkovskii** [comment]
> Is there a way to delete this one?
May be a big white button "Close pull request"?

**Comment by akrasuski1** [comment]
Oh, ok. I thought it just "closes" it, in the sense that one cannot add any more commits, but it can be still merged.

**Comment by abenkovskii** [comment]
I think that "can be merged" means that it has no conflicts with the current contents of the repository. All closed issues and PRs are saved for history.

**Comment by akrasuski1** [comment]
Hmm, shall I call the action I meant "pulled" then? Or is there other word for "applying the pull request"?

**Comment by abenkovskii** [comment]
No I just didn't read your comment carefully enough. I thought that you are talking

**Pull request closed without merging**
